### ISSUE TITLE
Behavior change: runPlay depends on test?

### ISSUE THREAD

**Issue by aaronlijie** [gradle/playframework#101]
Hi
When I trigger runPlay tasks under new playFramework, I found test task is also executed.
I thought it is due to this line: [playRun.dependsOn(project.getTasks().named(BUILD_TASK_NAME))](https://github.com/gradle/playframework/blob/95e68fe1a90dc40b9ce8b704e1c902369a67490c/src/main/java/org/gradle/playframework/plugins/PlayApplicationPlugin.java#L165)

I think under old playFramework, Running runPlayBinary will not rigger test/ check task. So could we change the new playFramework to make the behavior same as old one?

**Comment by bmuschko** [comment]
It looks like the "old" plugin also [depends on the `build` task](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayApplicationPlugin.java#L319) though its dependencies might look different with the software model. It sounds reasonable to me to _not_ depend on the `test` task for running the application. Care to work on a pull request for this?

**Comment by aaronlijie** [comment]
I think it is enough to make the runPlay task depend on [mainJarTask](https://github.com/gradle/playframework/blob/95e68fe1a90dc40b9ce8b704e1c902369a67490c/src/main/java/org/gradle/playframework/plugins/PlayApplicationPlugin.java#L67) and [assetsJarTask](https://github.com/gradle/playframework/blob/95e68fe1a90dc40b9ce8b704e1c902369a67490c/src/main/java/org/gradle/playframework/plugins/PlayApplicationPlugin.java#L68). How is your opinion?

**Comment by bmuschko** [comment]
That sounds right. It's probably a good idea to run a Play application with the "old" plugin to compare.

**Comment by aaronlijie** [comment]
@bmuschko I have created a pull request. Feel free to review.

**Comment by big-guy** [comment]
This is fixed in 0.7
