### ISSUE TITLE
Please release 0.10 from current master to fix Play 2.3 support

### ISSUE THREAD

**Issue by mikaelnousiainen** [gradle/playframework#134]
The latest release is broken for Play 2.3 because of #93, so a new release would be welcome :)

**Comment by JLLeitschuh** [comment]
We have some failing tests on master. If someone were to contribute a PR fix to make these tests pass, I can push to get a release shipped. See #136

**Comment by cstroe** [comment]
CI build is fixed in https://github.com/gradle/playframework/pull/147

**Comment by borowis** [comment]
:tada: I think that was fixed and released. @mikaelnousiainen do you have a button to close the issue? :laughing:

**Comment by JLLeitschuh** [comment]
My understanding is that this is fixed. If this proves not to be the case, please open a new issue.
