### ISSUE TITLE
Plugin Status

### ISSUE THREAD

**Issue by h-ngo** [gradle/playframework#145]
The release of this plugin has been pretty inactive. The last final release happened back in Aug 2019. In fact, to support our Play 2.7 upgrade last year, our team had to add Play 2.7 support to the plugin and manually build it (https://github.com/gradle/playframework/pull/110). However, we don't think this is a good idea going forward as we have limited knowledge of the innerworkings of the whole plugin.

As Play framework continues publishing new releases, it's very important for us to pick the right build tool and plugin to actively support our development. Moreover, with the pace of Gradle release, we will be heavily rely on a migration guide which seems to be missing from the plugin.

Hence, we would like to inquiry about the status of the plugin as well as its roadmap, so we can better decide whether to keep using Gradle or better off to consider other build tool options to support Play Framework.

@big-guy @bmuschko

**Comment by JLLeitschuh** [comment]
See the discussion on #135 and #136
