### ISSUE TITLE
Play IDE plugin: Write plugin implementation class with current model

### ISSUE THREAD

**Issue by bmuschko** [gradle/playframework#39]
- Convert existing logic from software model to current model
- Only supports IntelliJ IDEA
- Mapping of configurations to IDEA scopes
- Mapping of source/target byte code version
- Mapping of source directories

**Note: We should see IntelliJ can just import a Play project without the needs to implement this plugin**

**Comment by big-guy** [comment]
Did you try removing things like:
https://github.com/gradle/play/blob/2e12a26ac1c2ad3be978bdbabea2d856af7d189f/src/main/java/com/lightbend/play/plugins/PlayIdeaPlugin.java#L69-L73

It seems to me that this should "just work" since we're reusing the main source set now for scala.
