### ISSUE TITLE
Implement multi-version integration testing

### ISSUE THREAD

**Issue by bmuschko** [gradle/playframework#41]
- A selection of existing integration tests can be run with multiple versions of Play
- TestKit does not have built-in support for it
- Implement a JUnit rule to allow running tests multiple times

**Note: We do not know yet what the supported versions of Play should be. This depends on customers of the plugin giving us the information.**

**Comment by big-guy** [comment]
@bmuschko is this the catch all issue for any test that needs multi-version support?

Could you list the tests that are affected by this here?

**Comment by big-guy** [comment]
e.g., `TwirlVersionIntegrationTest.groovy` uses multiple versions, but it doesn't appear to be a "multi-version" test because it's not parameterized based on the version of Play.

**Comment by bmuschko** [comment]
@big-guy This is a catch-all issue. Let me know if you'd like me to make this an epic. My plan was to introduce a base class for multi-version testing and use it for all classes that will later need to support cross-version compatibility. Simply didn't get around to doing it yet.

**Comment by bmuschko** [comment]
@big-guy I somewhat prepared this work item. I introduced a parent class `com.lightbend.play.PlayMultiVersionIntegrationTest` that indicates that a test should be run with multiple Play versions later.

**Comment by bmuschko** [comment]
Implementation:

- Fixtures: https://github.com/gradle/play/tree/master/src/integTestFixtures/groovy/org/gradle/playframework/fixtures/multiversion
- Usage: https://github.com/gradle/play/blob/master/src/integTest/groovy/org/gradle/playframework/PlayMultiVersionIntegrationTest.groovy#L10-L11

I wrote an implementation that can provide a combination of compatible Play & Scala version. By default, the multi-versions tests are only run with the latest Play version. On CI the all versions are executed. A system property can control the set of versions that should be run from the command line. Given that it takes very long to run all tests, we might want to think about running them in parallel on CI.

**Comment by big-guy** [comment]
LGTM, thanks Ben
