### ISSUE TITLE
New plugin should use configuration avoidance APIs from the start

### ISSUE THREAD

**Issue by big-guy** [gradle/playframework#49]
`named`, `register`, etc.

We can fix this when the tasks are migrated over.

**Comment by bmuschko** [comment]
Implementation: https://github.com/gradle/play/commit/2e12a26ac1c2ad3be978bdbabea2d856af7d189f

**Comment by big-guy** [comment]
We should have a "well behaved" integration test that checks that when we run `help` with the play plugin applied, it doesn't create tasks.

**Comment by big-guy** [comment]
In TwirlSourceSet:

```
Provider<TwirlImports> getDefaultImports();
void setDefaultImports(Provider<TwirlImports> defaultImports);
void setDefaultImports(TwirlImports defaultImports);

Provider<List<TwirlTemplateFormat>> getUserTemplateFormats();
void setUserTemplateFormats(Provider<List<TwirlTemplateFormat>> userTemplateFormats);
void setUserTemplateFormats(List<TwirlTemplateFormat> userTemplateFormats);
void addUserTemplateFormat(final String extension, String templateType, String... imports);

Provider<List<String>> getAdditionalImports();
void setAdditionalImports(Provider<List<String>> additionalImports);
void setAdditionalImports(List<String> additionalImports);
```

These should just be:
```
Property<TwirlImports> getDefaultImports();

ListProperty<TwirlTemplateFormat> getUserTemplateFormats();
TwirlTemplateFormat newTemplateFormat(final String extension, String templateType, String... imports);

ListProperty<String>> getAdditionalImports();
```

This would look something like this in the DSL:
```
sourceSets {
    main {
        twirl {
            defaultImports = TwirlImports.JAVA

            userTemplateFormats.add(newTemplateFormat("unused", "views.formats.unused.UnusedFormat"))

            additionalImports = [ 'my.pkg._', 'my.pkg.MyClass' ]
        }
    }
}
```

**Comment by big-guy** [comment]
This should be using the Property from the task:
https://github.com/gradle/play/blob/2e12a26ac1c2ad3be978bdbabea2d856af7d189f/src/main/java/com/lightbend/play/plugins/PlayApplicationPlugin.java#L125-L127

```
scalaSourceDirectorySet.srcDir(getTwirlCompileTask(project).flatMap(task -> task.getOutputDirectory());
scalaSourceDirectorySet.srcDir(getRoutesCompileTask(project).flatMap(task -> task.getOutputDirectory());
```

**Comment by big-guy** [comment]
I've seen this in many different places, so I'll leave this as a general comment/guidance:

- When there's a configurable `Property`, there should be a single getter that returns `Property<Whatever>`.  There should not be any other setter or getter.
- If there's a FileCollection that needs to be configurable, make a single getter that returns a `ConfigurableFileCollection` and not `FileCollection` + a setter. I see this in every task that has a classpath.
- Similar to above, we shouldn't have a getter with `Provider<List<...>>`, these should just be `ListProperty<...>`.
- As a style nit, if something is an output directory property, the `dir` is spelled out (so `destinationDirectory` over `destinationDir`).

**Comment by bmuschko** [comment]
- https://github.com/gradle/play/commit/1174f1f23cea9cf780334652783e389015fa985c
- https://github.com/gradle/play/commit/e784829bbcabd6f8c78da774d1e46768eaa8929d

> As a style nit, if something is an output directory property, the dir is spelled out (so destinationDirectory over destinationDir).

This is still the same name as it was in Gradle core. I can change that after doing some more important items.

**Comment by bmuschko** [comment]
As a side note: The preferred rules for using the lazy configuration API are not documented well in the user guide. It kind of explains it but I wouldn't really have found it. Maybe the bigger code examples should rather use Java instead of Groovy to make things more clear.

**Comment by big-guy** [comment]
Can you add a integration test that does the same thing as:
https://github.com/gradle/gradle/blob/d5ca656bb73d3347bbf6926f3c1faf01d259aff6/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy#L93-L106

The test just needs to apply play + idea. It's OK if we're not completely lazy right now, I just want to see how close we are and prevent future tasks/plugins from adding more.

**Comment by bmuschko** [comment]
Added the test here: https://github.com/gradle/play/commit/68dfbd4e1a9ae972ca4e9c30c62120a0b9c12c1a

Right now the list of realized tasks looks like this: `[':createPlayAssetsJar', ':minifyPlayJavaScript', ':compilePlayTwirlTemplates', ':jar', ':distZip', ':distTar', ':compileJava', ':processResources', ':help']`. I am sure that we can eliminate the `dist` tasks but I haven't found the spot that actually does realize them.

**Comment by bmuschko** [comment]
@big-guy Did you have a chance to look at this?

**Comment by big-guy** [comment]
The dist tasks might go away with a newer version of Gradle.  Can we put these tasks in as the expected state so it doesn't get worse?

**Comment by bmuschko** [comment]
> The dist tasks might go away with a newer version of Gradle.

Do you mean the `dist` task in the "old" Play plugin or which one specifically?

> Can we put these tasks in as the expected state so it doesn't get worse?

Meaning make sure that they don't get realized?

**Comment by big-guy** [comment]
> Do you mean the dist task in the "old" Play plugin or which one specifically?

It looks like the PlayDistribution plugin in this repo applies the regular `distribution` plugin, but since you're testing with Gradle 5.0, I think those weren't made lazy until 5.1.  So they'll "go away" from the realized list when you upgrade to a newer version of Gradle.

>> Can we put these tasks in as the expected state so it doesn't get worse?
> Meaning make sure that they don't get realized?

I mean that instead of marking the test as not implemented, you just assert that all of those tasks are realized for now.

**Comment by bmuschko** [comment]
> It looks like the PlayDistribution plugin in this repo applies the regular `distribution` plugin, but since you're testing with Gradle 5.0, I think those weren't made lazy until 5.1. So they'll "go away" from the realized list when you upgrade to a newer version of Gradle.

The tasks are still realized even after the upgrade. Maybe it's because we are accessing the `DistributionContainer` and the `Distribution` instances provided by the Distribution plugin?

> I mean that instead of marking the test as not implemented, you just assert that all of those tasks are realized for now.

done

**Comment by big-guy** [comment]
great, thanks!
