### ISSUE TITLE
Rework Play plugins to use Java/Scala plugin configurations

### ISSUE THREAD

**Issue by big-guy** [gradle/playframework#55]
PlayPluginConfigurations was used to bridge between the software model and Configurations.

We should use the built-in compile/test/runtime configurations instead of special Play ones.

It's OK to keep the playPlatform configuration

**Comment by big-guy** [comment]
This would simplify the test and IDE plugins and maybe make them unnecessary beyond just applying "conventions".

**Comment by big-guy** [comment]
As a start https://github.com/gradle/playframework/commit/6e53f9c37660af9b1121e4adf2f4d0f1c950040e

**Comment by bmuschko** [comment]
Did this one as PR due to the many changes.

Implementation: https://github.com/gradle/playframework/pull/89
