### ISSUE TITLE
Implement smoke test of the plugin in gradle/gradle

### ISSUE THREAD

**Issue by bmuschko** [gradle/playframework#58]
Implement a smoke test that use uses the latest, published version of the plugin (or the current code base on `master`) and run a basic use case against the minimum supported version of Gradle for this plugin.

**Comment by big-guy** [comment]
We should also consider putting a smoke test into gradle/gradle that uses a particular version of this plugin.

**Comment by bmuschko** [comment]
Gradle core would be the best place to put this test. It already has the infrastructure and the core team would know immediately if something breaks.

**Comment by pioterj** [comment]
I think this is exactly what we should do and the version should be latest.

> We should also consider putting a smoke test into gradle/gradle that uses a particular version of this plugin.

This is important as it addresses the risk of using internal APIs. 

I updated the title of the issue accordingly. 

The plugin will have its own extensive coverage.

**Comment by pioterj** [comment]
@bmuschko It would be good to check if all used internal APIs are covered by the smoke test and add additional smoke tests if needed. I guess we could do this with a simple code coverage report.

**Comment by bmuschko** [comment]
@pioterj I have a couple of comments about this:

1. The use of internal APIs is not limited to production source code. Some of them are also used in the test fixtures I moved over. Given the time constraints I couldn't get rid of all of them. Examples: `org.gradle.util.CollectionUtils` or `org.gradle.util.VersionNumber`. That means that a change to Gradle core's internal APIs could also break the tests in this plugin.
2. The use of internal APIs in the production source code spans most prominent use cases. Ultimately, a smoke test would have to build _and_ run the application in continuous mode if you wanted to have good coverage.
3. Smoke testing in Gradle core is done with TestKit which means we have the same issue as https://github.com/gradle/playframework/issues/58 for them. Without the proper changes in Gradle core we won't be able to effectively implement those test cases.
4. A code coverage report is a good idea. Tests executed with TestKit run in a different JVM. If you use JaCoCo, you'd need to attach a JVM agent to the target JVM which is not straight forward without adding custom code as described in https://github.com/gradle/gradle/issues/1465.

**Comment by pioterj** [comment]
I see. Is this blocked by https://github.com/gradle/playframework/issues/38 then?

**Comment by bmuschko** [comment]
I'd say "half-blocked". ;-) We can write a smoke test that builds a Play application but that doesn't run it.

Another effective way to reduce the risk is to simply replace the use of the Gradle internal API with something else e.g. plain Java, an external library or by pulling in some of the Gradle core code into the plugin.

**Comment by pioterj** [comment]
OK, sounds like a case by case decision. Let me take back what I said about "all" APIs. I don't think it's a requirement that we have usage of all internal APIs covered by smoke tests.

**Comment by big-guy** [comment]
Some of the weirdness you were seeing with the smoke test is probably from #82 - there are breakages already :/

**Comment by bmuschko** [comment]
Yikes, maybe it's a good idea to remove as many of the reliance on internal APIs as possible. There are definitely some quick wins in the code base. In the long run, the Gradle team should probably also look into exposing new public APIs for some of the functionality used by this plugin.

**Comment by big-guy** [comment]
I can help get a 0.2 published and we can try this again once we close out the 5.2 upgrade issue

**Comment by bmuschko** [comment]
@big-guy When running the smoke test using Play plugin 0.2 I get an error that the internal class `org.gradle.scala.internal.reflect.ScalaMethod` cannot be resolved. See [build scan](https://scans.gradle.com/s/dyoqatpeg3gei/tests/iptsm6im6po76-b3pbluudtpbrq). I don't fully understand why this is happening. Maybe because Gradle needs to be run with Java 9+? Should we move the classes of package `org.gradle.scala.internal.reflect` into the plugin? I'd think you'll want to get rid of them in the long run anyway.

**Comment by bmuschko** [comment]
Implementation: https://github.com/gradle/gradle/pull/8459

**Comment by big-guy** [comment]
Thanks @bmuschko  - I've triggered the smoke tests on TC and i'll take a look.

**Comment by big-guy** [comment]
Merged, thanks Ben
