### ISSUE TITLE
Publish initial version of external plugins and documentation

### ISSUE THREAD

**Issue by big-guy** [gradle/playframework#66]

**Comment by pioterj** [comment]
test Slack integration

**Comment by bmuschko** [comment]
1. We need to nail down the name of GitHub repository as we use it for the publishing information: https://github.com/gradle/play/blob/master/build.gradle.kts#L106. i am not quite sure if that information is optional or mandatory.
2. For publishing to the Plugin Portal we should use a Gradle-owned account and not my personal account. I am not quite sure how hard it is to switch ownership on the portal after publishing a first version.

**Comment by bmuschko** [comment]
Blocked by https://github.com/gradle/play/issues/60

**Comment by bmuschko** [comment]
TODO Before publishing:

- Update the change log as needed including the date: https://github.com/gradle/play/blob/master/src/docs/asciidoc/50-changes.adoc

TODO After publishing:

- Tag the source code so we later reference it.
- Try out some of the links that reference the Javadocs of this plugin from the documentation.
- Try out an actual project with the released version.

**Comment by eskatos** [comment]
v0.1 is now [tagged](https://github.com/gradle/playframework/releases/tag/v0.1) and the plugins are now published and approved :tada:

https://plugins.gradle.org/plugin/org.gradle.playframework
https://plugins.gradle.org/plugin/org.gradle.playframework-application
https://plugins.gradle.org/plugin/org.gradle.playframework-distribution
https://plugins.gradle.org/plugin/org.gradle.playframework-ide
https://plugins.gradle.org/plugin/org.gradle.playframework-javascript
https://plugins.gradle.org/plugin/org.gradle.playframework-routes
https://plugins.gradle.org/plugin/org.gradle.playframework-test
https://plugins.gradle.org/plugin/org.gradle.playframework-twirl

Documentation available at https://gradle.github.io/playframework/
