### ISSUE TITLE
Plugin user guide should be publishable to GitHub Pages

### ISSUE THREAD

**Issue by bmuschko** [gradle/playframework#67]
- Add build code for publishing to GitHub pages
- Publishes the following artifacts:
    - The generated HTML version of the plugin user guide
    - The Javadocs of the plugin API so that classes can be referenced from user guide
- Documentation is available on GitHub pages
- Publishing to GitHub requires the creation of a GitHub token (needs to be owned by Gradle)

**Comment by bmuschko** [comment]
Implementation:

- https://github.com/gradle/play/commit/7bbaa8f38b563bd7088e78547fbc17157b1f3f4a

**Comment by big-guy** [comment]
Is this waiting on a Gradle person to publish?

**Comment by bmuschko** [comment]
@big-guy Two things actually:

1. Find a unique plugin ID: https://github.com/gradle/play/issues/60. We can't really continue until we nail that down as the plugin ID is referenced in the documentation.
2. I suggest that someone from Gradle core publishes the docs as you'd need a GitHub token generated from an Admin account.

**Comment by bmuschko** [comment]
@big-guy I changed the description of https://github.com/gradle/play/issues/66 to also include documentation. So you can go ahead and close this issue if you are happy with the code.
