### ISSUE TITLE
On CI, multi-versions tests should be executed in parallel

### ISSUE THREAD

**Issue by bmuschko** [gradle/playframework#75]
Executing the full set of integration tests including all versions currently [takes a long time](https://travis-ci.org/gradle/play/jobs/467663941) (~30 mins). We should think about a way to run them in parallel. The multi-version test runner already offers a way to run these tests for a given version.

- Option 1: Rename all multi-version thats with the suffix `*MultiVersionIntegrationTest`. On CI run the task `integrationTest` and provided a `--test` filter + the system property that define the version.
- Option 2: Move all multi-version tests to a new source set. A new test task can run these tests with a specific version by providing the system property.

Use [Travis CI's parallel execution feature](https://docs.travis-ci.com/user/speeding-up-the-build/). We already do this to [run integration tests and documentation tests in parallel](https://github.com/gradle/play/blob/master/.travis.yml#L7-L10).

**Comment by big-guy** [comment]
As a quick and dirty solution, could we also try running the integration tests with maxParallelForks > 1?

**Comment by bmuschko** [comment]
[We already do](https://github.com/gradle/playframework/blob/master/buildSrc/src/main/kotlin/org/gradle/playframework/TestSetupPlugin.kt#L17) but I guess it doesn't help much as a build job on Travis CI only has 1 CPU with 2 cores.

**Comment by marracuene** [comment]
> [We already do](https://github.com/gradle/playframework/blob/master/buildSrc/src/main/kotlin/org/gradle/playframework/TestSetupPlugin.kt#L17) but I guess it doesn't help much as [a build job on Travis CI only has 1 CPU with 2 cores](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system).

Please see these timings I have just posted...  indeed the long-runnning docTest is multi-version and in parallel... still takes ages.   https://github.com/gradle/playframework/issues/136#issuecomment-646020423

**Comment by cstroe** [comment]
Using Travis CI's Matrix build, we can break out the build by Play version.  The fix is in https://github.com/gradle/playframework/pull/147 , see the Travis CI build [here](https://travis-ci.org/github/gradle/playframework/builds/726525965)
