### ISSUE TITLE
Make samples work out of the box

### ISSUE THREAD

**Issue by pioterj** [gradle/playframework#76]
Currently building all of the samples fail as they don't set the version of the plugin.

The version is injected by TestKit in automated tests. 

Samples should also work out of the box for end users.

**Comment by pioterj** [comment]
Why JAR file and not just a ZIP for example?

**Comment by bmuschko** [comment]
My guess is that the Gradle plugin portal won't allow publishing files with a ZIP extension. It apparently has a built-in set of classifiers it will accept. Chatted about this with @eskatos and opened the issues https://github.com/gradle/gradle/issues/8271 and https://github.com/gradle/gradle/issues/8270 as a follow-up.

@eskatos Do you know if the plugin portal accepts ZIP files?
@pioterj I don't think we'll be able to upload a sample archive file. See https://github.com/gradle/gradle/issues/8271 for details. Happy to make it a ZIP file but usually Javadocs are also bundled/published in a JAR file.

**Comment by eskatos** [comment]
@bmuschko what I know is that it rejects unknown classifiers, so it won't help much except if you want to publish a `-<accepted-classifier>.zip`

**Comment by bmuschko** [comment]
@eskatos Yeah, I don't it's a good idea to bundle samples into something that doesn't represent its purpose. Do you have any near-term plans to make improvements to the plugin portal on that front?

**Comment by eskatos** [comment]
It's not planned. I wouldn't block this issue on it.

What about adding the latest version number to the samples so they work out of the box and having the build/fixtures strip the version out while asserting it's the correct version? This way we would have a safety net for out of sync versions. I assume the samples are copied to a temporary dir for the TestKit execution, this could happen at this time. wdyt?

**Comment by bmuschko** [comment]
> What about adding the latest version number to the samples so they work out of the box and having the build/fixtures strip the version out while asserting it's the correct version?

The reason I don't like it is that we are hard-coding versions in the samples and will likely forget about upgrading them in the future. But maybe that's just fine. We can get started with this approach.

**Comment by pioterj** [comment]
@bmuschko Including changes to the Plugin Portal in this conversation seems to be making it harder than it needs to be. I don't think it's a requirement that samples need to be published on the Plugin Portal. The main documentation isn't directly visible on the Plugin Portal either, you have to follow a link. Having samples linked from the documentation would be sufficient IMO. 

I like the simplicity of the option with just using the latest version number in the samples. I see the concern about forgetting to update them. Could we address it by some additional automation in the plugin build?

**Comment by bmuschko** [comment]
> Including changes to the Plugin Portal in this conversation seems to be making it harder than it needs to be. I don't think it's a requirement that samples need to be published on the Plugin Portal. The main documentation isn't directly visible on the Plugin Portal either, you have to follow a link. Having samples linked from the documentation would be sufficient IMO.

The issues I created are features requests for the plugin. They don't really block the implementation of this issue, however, it's how I'd like to provide samples for my own plugins. It's a bit weird that users have to check out source code with a specific tag to actually run through some samples. I see samples as a deliverable of a release similar to Javadocs and sources bundles in archives. It is one of the reasons I still prefer publishing my own plugins to JCenter in the first place and then sync with the plugin portal.

> I like the simplicity of the option with just using the latest version number in the samples. I see the concern about forgetting to update them. Could we address it by some additional automation in the plugin build?

Sure could. That would involve find the right places in the sample code, replacing the version with the one currently published, commit and pushing the code in an automated fashion. I see can how much effort it is.

**Comment by bmuschko** [comment]
Implementation (you can find comments on the design decisions in the commit message): https://github.com/gradle/playframework/commit/1bd59e88f69b952fa5c5d9ad986bcb0f155941ff
