### ISSUE TITLE
Links to Javadocs in user guide should work properly

### ISSUE THREAD

**Issue by bmuschko** [gradle/playframework#79]
The links to the referenced Javadocs are not quite right. For example the referenced class `TwirlSourceSet` points to a non-existing URL.

**Wrong:**
https://gradle.github.io/playframework/org.gradle.playframework.sourcesets.TwirlSourceSet.html

**Correct:**
https://gradle.github.io/playframework/api/org/gradle/playframework/sourcesets/TwirlSourceSet.html

**Comment by bmuschko** [comment]
Implementation: https://github.com/gradle/playframework/commit/8691d3f4c785e37a13b1978a6124f8d805920ac7

**Comment by big-guy** [comment]
why is there no javadoc for the methods/classes that have comments?

**Comment by bmuschko** [comment]
You'll have to republish the Javadocs and user guide for the changes to show up. Maybe @eskatos can help with this. He did it last time.

**Comment by eskatos** [comment]
The instructions in the README just worked for me: https://github.com/gradle/playframework/blob/master/README.adoc#generating-documentation

**Comment by big-guy** [comment]
I regenerated the javadoc and it looks right now
