### ISSUE TITLE
Update to Gradle 5.2

### ISSUE THREAD

**Issue by big-guy** [gradle/playframework#82]
I think some changes were made to internal reflection APIs that break this plugin.

Maybe we can just duplicate the reflection methods used and keep it all in this repo or eliminate reflection APIs in cases where there's only a single version of a type/interface we need.

**Comment by bmuschko** [comment]
> Maybe we can just duplicate the reflection methods used and keep it all in this repo or eliminate reflection APIs in cases where there's only a single version of a type/interface we need.

Can you point me to those?

**Comment by big-guy** [comment]
Hrm, I thought there were more, but it looks like it's just the Closure compiler that doesn't really need reflection.

All of the other tools (routes, twirl and play run) have two or more versions they support and rely on reflection.  It would be ugly, but one way to deal with this would be to split out the version specific tool code into a separate subproject and have compileOnly dependencies on specific versions.

So you'd have a routes-2.3 and a routes-2.4 subproject that contains the version specific implementations of RoutesCompilerAdapterV23X and RoutesCompilerAdapterV24X.  You'd avoid the reflection that way.

**Comment by bmuschko** [comment]
Instead of reworking the project hierarchy, I decided to migrate some of the reflection classes.

Implementation: https://github.com/gradle/playframework/compare/17c89f9e1da3...c34bbd2f1600

**Comment by big-guy** [comment]
It looks OK to me

I see a local build failure: https://scans.gradle.com/s/fh6jmp6od6jvc/tests/52hmxbpuo2cl2-4n4qeb5cq47vw

The play-2.4 sample fails and the play-2.6 sample is skipped.  Do you see the same?

**Comment by bmuschko** [comment]
This might be an issue with Java 11. I am running locally with Java 8 and that works fine for me. We use Java 8 on CI as well.

I am not sure if [this overview](https://gradle.github.io/playframework/#play_framework) is still correct but can you even use a newer Java version that 8? The table indicates that you can't.

**Comment by big-guy** [comment]
Yep, you're right.  I forgot Java 11 didn't work
