### ISSUE TITLE
testAnnotationProcessor does not work with play plugin

### ISSUE THREAD

**Issue by big-guy** [gradle/playframework#84]
@jasongilanfarr commented on [Wed Jan 30 2019](https://github.com/gradle/gradle/issues/8378)

annotationProcessor(...lombok...) works for play projects for compilePlayBinaryScala; however, testAnnotationProcessor(...lombok...) does not seem to enable annotation processing in compilePlayBinaryTests. 

As far as I can tell, there is no play/playTestAnnotationProcessor

---

@big-guy commented on [Wed Jan 30 2019](https://github.com/gradle/gradle/issues/8378#issuecomment-459168040)

There's not a separation between the annotationProcessor classpath and the regular classpath in the Play plugin.

As a workaround, could you try:
```
model {
    tasks.compilePlayBinaryTests { 
      options.annotationProcessorPath = classpath
    }
}
```
and use the `playTest` configuration to add the annotation processor.

**Comment by big-guy** [comment]
The new plugins should leverage what the Java/Scala plugins do.

I think #55 would help a bit.

**Comment by bmuschko** [comment]
> The new plugins should leverage what the Java/Scala plugins do.

Can you give more details here? Is this a blocker for adoption?

I guess the workaround for the new plugin would look similar to the one for the "old" plugin.

```
compileTestScala {
    options.annotationProcessorPath = classpath
}
```

**Comment by big-guy** [comment]
This isn't complete, but something like this: https://github.com/gradle/playframework/commit/6e53f9c37660af9b1121e4adf2f4d0f1c950040e

It's mostly removing `PlayPluginConfigurations` and along with that the play/playTest/playRun configurations in favor of implementation/testImplementation/etc (or compile/testCompile/runtime...).  The one custom configuration for Play is the addition of the `play` configuration which is a parent of compile. This isn't 100% necessary, but it kept the samples more similar. 

These sorts of things aren't necessary if we allow the Java plugin to do everything:
https://github.com/gradle/playframework/blob/master/src/main/java/org/gradle/playframework/plugins/PlayApplicationPlugin.java#L139

This wasn't possible with the software model plugins because everything was built from scratch.

So we can strip out all of the custom configuration for ScalaCompile tasks and I *think* the PlayIDE, PlayTest and PlayDistribution plugins go away or become simple.  They should just be conventions put on top of the existing plugins.

**Comment by bmuschko** [comment]
@big-guy Thanks for the background info. Would you consider this a must-have feature? If you do then we should add it to the epic https://github.com/gradle/playframework/issues/70 and I should likely work on it soon.

**Comment by bmuschko** [comment]
@big-guy Now that we merged https://github.com/gradle/playframework/pull/89, I think we can close the issue. Correct? [This test case](https://github.com/gradle/playframework/blob/master/src/integTest/groovy/org/gradle/playframework/application/dependencies/PlayJavaAnnotationProcessingIntegrationTest.groovy) describes how to use an annotation processor.

**Comment by big-guy** [comment]
Yeah, looks like that's the case now
