### ISSUE TITLE
NPE when compiling routes with Play 2.3.X

### ISSUE THREAD

**Issue by novokrest** [gradle/playframework#93]
Reproduced for Play plugin version **2.3.X**.

`NullPointerException` throws at `RoutesCompiler#execute` on 42th line, because `null` is returned from `RoutesCompiler#compile` method. The problem is that `RoutesCompilerAdapterV23X#interpretResult` try to cast result of `play.router.RoutesCompiler#compile` invocation to `Boolean`, but the returned value from `play.router.RoutesCompiler#compile` has `void` as type. So, invocation of `play.router.RoutesCompiler#compile` by reflection returns `null` which eventually is tried to unbox to `boolean` in `RoutesCompiler#execute` method.

**Comment by emersonf** [comment]
Thanks for fixing this.

Would it be possible to release an updated plugin with this fix included please?

**Comment by emersonf** [comment]
Judging by recent activity, I'm guessing I should ping @big-guy :) Are there any imminent releases planned?
