### ISSUE TITLE
createXxxxDistributionJar behaves different under new playframework

### ISSUE THREAD

**Issue by aaronlijie** [gradle/playframework#95]
Hi,
I am testing the new playframework plugin, and find the task createXxxxxxxDistributionJar behaves different under new plugin.

How to reproduce:
check out the sample of original play plugin [play 2.4](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/play/play-2.4) and execute createPlayBinaryDistributionJar task.
The MANIFEST under build/tmp/createPlayBinaryDistributionJar looks like:
```
Manifest-Version: 1.0
Class-Path: commons-lang-commons-lang-2.6.jar com.typesafe.play-play-d
 ocs_2.11-2.4.0.jar com.typesafe.play-play-netty-server_2.11-2.4.0.jar
  com.typesafe.play-play-server_2.11-2.4.0.jar com.typesafe.play-play_
 2.11-2.4.0.jar com.typesafe.play-play-json_2.11-2.4.0.jar com.typesaf
 e.play-play-iteratees_2.11-2.4.0.jar com.typesafe.play-play-doc_2.11-
 1.2.2.jar com.typesafe.play-twirl-api_2.11-1.1.1.jar org.scala-lang.m
 odules-scala-parser-combinators_2.11-1.0.1.jar com.typesafe.akka-akka
 -slf4j_2.11-2.3.11.jar com.typesafe.akka-akka-actor_2.11-2.3.11.jar o
 rg.scala-stm-scala-stm_2.11-0.7.jar org.scala-lang-scala-reflect-2.11
 .6.jar com.typesafe.play-play-functional_2.11-2.4.0.jar com.typesafe.
 play-play-datacommons_2.11-2.4.0.jar org.scala-lang.modules-scala-xml
 _2.11-1.0.1.jar org.scala-lang-scala-library-2.11.6.jar com.typesafe.
 play-build-link-2.4.0.jar com.typesafe.play-play-netty-utils-2.4.0.ja
 r org.slf4j-jul-to-slf4j-1.7.12.jar org.slf4j-jcl-over-slf4j-1.7.12.j
 ar ch.qos.logback-logback-classic-1.1.3.jar org.slf4j-slf4j-api-1.7.1
 2.jar ch.qos.logback-logback-core-1.1.3.jar com.fasterxml.jackson.dat
 atype-jackson-datatype-jdk8-2.5.3.jar com.fasterxml.jackson.datatype-
 jackson-datatype-jsr310-2.5.3.jar com.fasterxml.jackson.core-jackson-
 databind-2.5.3.jar com.fasterxml.jackson.core-jackson-core-2.5.3.jar 
 com.fasterxml.jackson.core-jackson-annotations-2.5.3.jar commons-code
 c-commons-codec-1.10.jar joda-time-joda-time-2.7.jar org.joda-joda-co
 nvert-1.7.jar org.apache.commons-commons-lang3-3.4.jar xerces-xercesI
 mpl-2.11.0.jar javax.transaction-jta-1.1.jar com.google.inject.extens
 ions-guice-assistedinject-4.0.jar com.google.inject-guice-4.0.jar com
 .typesafe.play-play-exceptions-2.4.0.jar org.javassist-javassist-3.19
 .0-GA.jar com.typesafe-config-1.3.0.jar xml-apis-xml-apis-1.4.01.jar 
 javax.inject-javax.inject-1.jar aopalliance-aopalliance-1.0.jar com.g
 oogle.guava-guava-16.0.1.jar com.typesafe.netty-netty-http-pipelining
 -1.1.4.jar io.netty-netty-3.10.3.Final.jar org.pegdown-pegdown-1.4.0.
 jar commons-io-commons-io-2.4.jar org.parboiled-parboiled-java-1.1.5.
 jar org.parboiled-parboiled-core-1.1.5.jar org.ow2.asm-asm-analysis-4
 .1.jar org.ow2.asm-asm-util-4.1.jar org.ow2.asm-asm-tree-4.1.jar org.
 ow2.asm-asm-4.1.jar play-2.4-assets.jar
```
check out the sample of new play plugin [play 2.4](https://github.com/gradle/playframework/tree/master/src/docs/samples/play-2.4/groovy) and execute createMainDistributionJar task.
The MANIFEST under build/tmp/createPlayBinaryDistributionJar looks like:
```
Manifest-Version: 1.0
Class-Path: play-2.4.jar play-2.4-assets.jar
```
It seems the new one missed all classpath. Would you like to look into it? I suppose both plugins should generate same output.

**Comment by bmuschko** [comment]
I will likely have a look at it tomorrow. Quick question from my end: Do you use the generate JAR from this task to actually run the application? My guess is that it is missing the runtime dependencies from that list because we decided to get rid of the "old" custom configurations and opted for the standard configurations (e.g. `implementation`).

**Comment by bmuschko** [comment]
I created a PR for this: https://github.com/gradle/playframework/pull/96

**Comment by aaronlijie** [comment]
> I will likely have a look at it tomorrow. Quick question from my end: Do you use the generated JAR from this task to actually run the application? If this is _just_ a distribution then the Manifest entries shouldn't matter too much as long as the contents are correct.
> 
> My guess is that it is missing the runtime dependencies from that list because we decided to get rid of the "old" custom configurations and opted for the standard configurations (e.g. `implementation`).

Hi, Thanks for your reply.
Actually we use the generated JAR from this task to actually run/deploy the application

**Comment by bmuschko** [comment]
@aaronlijie Any chance you could try out the changes in https://github.com/gradle/playframework/pull/96 locally before we release a new version?

**Comment by aaronlijie** [comment]
> @aaronlijie Any chance you could try out the changes in #96 locally before we release a new version?

Hi @bmuschko Thank you for your reply. I would like to try but right now we have an issue with this new playframework (getArtifact).

In the new PlayApplicationPlugin.java, you set artifact as following:
[registerOutgoingArtifact](https://github.com/gradle/playframework/blob/95e68fe1a90dc40b9ce8b704e1c902369a67490c/src/main/java/org/gradle/playframework/plugins/PlayApplicationPlugin.java#L139)
```
PublishArtifact jarArtifact = new LazyPublishArtifact(assetsJarTask);
        ConfigurationPublications publications = runtimeElementsConfiguration.getOutgoing();
        publications.getArtifacts().add(jarArtifact);
        publications.getAttributes().attribute(ArtifactAttributes.ARTIFACT_FORMAT, ArtifactTypeDefinition.JAR_TYPE);
```
In the past, you set as following:[createBinaries](https://github.com/gradle/gradle/blob/d09ae3c685435c98d5ad4dd62c1573d9e5753ab7/subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayApplicationPlugin.java#L174)
```
configurations.getPlay().addArtifact(new DefaultPublishArtifact(projectIdentifier.getName(), "jar", "jar", null, new Date(), mainJar, playBinaryInternal));
                    configurations.getPlay().addArtifact(new DefaultPublishArtifact(projectIdentifier.getName(), "jar", "jar", "assets", new Date(), assetsJar, playBinaryInternal));
```
Due to this change, we couldn't get artifact when createXxxxDistributionJar is executed. I am trying to figure out the reason.

**Comment by bmuschko** [comment]
@aaronlijie Please open new issues if you encounter other problems. We'd also need more information like stack trace, what task has been run etc to be able to help you.

**Comment by aaronlijie** [comment]
> @aaronlijie Any chance you could try out the changes in #96 locally before we release a new version?

@bmuschko Hi, I have tried and it worked for us. Thank you for the fixing.

**Comment by bmuschko** [comment]
This has been released.
